version: "3.9"

services:
  api:
    build: .
    container_name: realtime_ml_api
    env_file:
      - .env
    volumes:
      - ./artifacts:/app/artifacts
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - flyway

  postgres:
    image: postgres:16-alpine
    container_name: realtime_ml_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:10-alpine
    container_name: realtime_ml_flyway
    command: -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres
