CREATE TABLE IF NOT EXISTS model_registry
(
    id SERIAL PRIMARY KEY,
    model_version VARCHAR(32) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
